name: aksessuar_emp_admin
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #firebase
  firebase_core: ^2.29.0
  cloud_firestore: ^4.16.1
  firebase_storage: ^11.7.1

  #hive
  hive: ^2.2.3
  path_provider: ^2.1.1
  path: ^1.8.3
  flutter_secure_storage: ^9.0.0

  #state management
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  provider: 6.0.5
  rxdart: ^0.27.7

  #dependency injection
  get_it: ^7.6.8

  #networking dependencies
  internet_connection_checker: ^1.0.0+1
  connectivity_plus: ^5.0.2

  #for ui
  cached_network_image: ^3.3.0
  intl: ^0.19.0
  scrollable_list_tab_scroller: ^1.1.2
  scroll_to_index: ^3.0.1
  lottie: ^3.1.0
  flutter_svg: ^2.0.10+1
  carousel_slider: ^4.2.1
  permission_handler: ^11.3.0
  flutter_native_splash: ^2.4.0
  google_fonts: ^6.2.1

  cupertino_icons: ^1.0.6

dev_dependencies:
  build_runner: ^2.4.9
  hive_generator: ^2.0.1

  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/image/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
