// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpFJ3kozk7KiD7WIEYV65Z5jJVy9b8Qmk',
    appId: '1:133268794215:web:e7bfeb9e842c1a4092ddc2',
    messagingSenderId: '133268794215',
    projectId: 'aksessuar-employ',
    authDomain: 'aksessuar-employ.firebaseapp.com',
    storageBucket: 'aksessuar-employ.appspot.com',
    measurementId: 'G-C7VE3MWB32',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiGVDOXfQWKqOMoOSfbWoP3NS0vKmwxgU',
    appId: '1:133268794215:android:fabc423a067f318492ddc2',
    messagingSenderId: '133268794215',
    projectId: 'aksessuar-employ',
    storageBucket: 'aksessuar-employ.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDamj3JqLDL9h2E9ZdzeMKnhBKCU0tVT2w',
    appId: '1:133268794215:ios:b30170991e77ef4b92ddc2',
    messagingSenderId: '133268794215',
    projectId: 'aksessuar-employ',
    storageBucket: 'aksessuar-employ.appspot.com',
    androidClientId: '133268794215-p5pmss46hbfeo21an4du0kba4las72bv.apps.googleusercontent.com',
    iosClientId: '133268794215-hqiv1ar7s821sqvae6bvgpj7o7d16gvr.apps.googleusercontent.com',
    iosBundleId: 'com.jtolibov.aksessuarEmpAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpFJ3kozk7KiD7WIEYV65Z5jJVy9b8Qmk',
    appId: '1:133268794215:web:e46a966eb511f30392ddc2',
    messagingSenderId: '133268794215',
    projectId: 'aksessuar-employ',
    authDomain: 'aksessuar-employ.firebaseapp.com',
    storageBucket: 'aksessuar-employ.appspot.com',
    measurementId: 'G-FTGXMNB01Y',
  );

}